controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_task_index:
    path: /
    controller: App\Controller\TaskController::index
update_task_status:
    path: /update-task-status
    controller: App\Controller\TaskController::updateTaskStatus
    methods: [POST]