controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

update_task_status:
    path: /update-task-status
    controller: App\Controller\TaskController::updateTaskStatus
    methods: [POST]